### ISSUE TITLE
Laura cannot login

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#481]
The app is saying that Laura does not have permission to access the app.

Her email address is laura@global-m.co.uk

**Comment by SimonLab** [comment]
Laura might already have an old cookie stored on her browser. Can she try to close Chrome completely and try to login again?

**Comment by Adam-JF** [comment]
I told Laura so remove access to the app from the permissions part of her google account and then re-login.

I also asked her to close chrome completely.

Neither solution worked and its still saying she doesn't have permission. I've double checked everything on accounts though and there doesn't appear to be anything out of the ordinary.

**Comment by SimonLab** [comment]
I'm going to delete completely Laura's account and create it again, it might resolve the problem. Also does Laura use Safari or Chrome? We are using a cookie to create a session to login into the application so if there is a tool which block the creation of the cookies she won't be able to login. First let's try with a new account and if the problem persists we will need to check the logs on Laura's browser

**Comment by Adam-JF** [comment]
It's not a browser issue. I tried logging into Laura's account from my own computer and also didn't have permission.

**Comment by SimonLab** [comment]
Thanks for testing this on your computer it helps us to filter why it's not working. I've recreated Laura's account, can you try to login again, thanks

**Comment by Adam-JF** [comment]
I've tried again and it still isn't working.

**Comment by SimonLab** [comment]
Technical tasks:
- [ ] On the first connection save the idGoogle to the profile in ES

**Comment by SimonLab** [comment]
@Adam-JF this issue should be resolved now. Can you try to log again with Laura's account and test the dashboard. However the old status you've created before won't work I still need to reset them. If you can send me by email the id of the profiles where you add some status I will reset them.

**Comment by Adam-JF** [comment]
It's back - Laura had the same message saying that she did not have permission to access the app.

**Comment by SimonLab** [comment]
@Adam-JF is it possible for you to connect with Laura's email? Let us know if you can and we will add some logs track the problem.

**Comment by heron2014** [comment]
@Adam-JF is Laura still have a problem with accessing the app?

**Comment by Adam-JF** [comment]
@heron2014 Yeah, unfortunately the issue is still there.

Last time we thought it might be an issue with her email address and whether or not the 'L' in laura@global-m.co.uk was capitalised or not

**Comment by heron2014** [comment]
@Adam-JF Thanks for the update. I have checked the database and it appeared that her email was still with the capital L, I have amended her email into the lowercase l. Please test it, if she still have problems with accessing the app.

**Comment by Adam-JF** [comment]
Laura was able to login fine now, thanks @heron2014
